/**
 * AI client for generating chess coaching explanations
 * Delegates the actual model call to the configured provider (Claude or Gemini)
 */

import { CoachingExplanation, CriticalMoment, CoachingContext } from './types';
import { buildCoachingPrompt } from './prompt-builder';
import { generateText } from './providers';
import { AIProvider } from '@/lib/types/storage';
import { logger } from '@/lib/utils/logger';
import { createAppError, wrapError } from '@/lib/utils/errorHandler';

const COACHING_SYSTEM_PROMPT = `You are a chess coach explaining a specific move in a game.
Your job is to help the player understand WHY the move was played and whether it was good or bad.
Be constructive, encouraging, and focus on learning.`;

/**
 * Generates a coaching explanation for a critical moment
 *
 * @param moment - The critical moment to explain
 * @param context - Context information about the position and move
 * @param apiKey - API key for the selected provider
 * @param skillLevel - Player skill level for personalization
 * @param provider - Which AI provider to use (default: 'claude')
 * @returns Coaching explanation generated by the provider
 * @throws AppError if the API call fails
 */
export async function generateExplanation(
  moment: CriticalMoment,
  context: CoachingContext,
  apiKey: string,
  skillLevel: 'beginner' | 'intermediate' | 'advanced' = 'intermediate',
  provider: AIProvider = 'claude',
): Promise<CoachingExplanation> {
  if (!apiKey || apiKey.trim().length === 0) {
    throw createAppError(
      'INVALID_API_KEY',
      `${provider === 'gemini' ? 'Gemini' : 'Anthropic'} API key is missing or empty`,
      `Please configure your ${provider === 'gemini' ? 'Gemini' : 'Anthropic'} API key in settings`,
      { skillLevel },
    );
  }

  const prompt = buildCoachingPrompt(context, skillLevel);

  try {
    logger.info('Generating coaching explanation', {
      provider,
      moveIndex: moment.moveIndex,
      reason: moment.reason,
      skillLevel,
    });

    const explanation = await generateText(provider, {
      apiKey,
      systemPrompt: COACHING_SYSTEM_PROMPT,
      prompt,
      maxTokens: 300,
    });

    logger.info('Explanation generated successfully', {
      provider,
      moveIndex: moment.moveIndex,
      explanationLength: explanation.length,
    });

    const alternatives = parseAlternativeMoves(explanation);

    return {
      moveIndex: moment.moveIndex,
      explanation,
      alternatives: alternatives.length > 0 ? alternatives : undefined,
      skillLevel,
      generatedAt: Date.now(),
    };
  } catch (error: unknown) {
    logger.error('Failed to generate explanation', error, { provider, moveIndex: moment.moveIndex });
    throw wrapError(error, {
      moveIndex: moment.moveIndex,
      skillLevel,
      provider,
    });
  }
}

/**
 * Parses alternative moves from explanation text
 * Looks for move notation patterns like "e2e4", "d4", etc.
 *
 * @param text - Explanation text to parse
 * @returns Array of alternative moves found
 */
function parseAlternativeMoves(text: string): string[] {
  const moves: Set<string> = new Set();

  // Match algebraic notation patterns (e.g., e2e4, d4, Nxe5)
  // This is a simple heuristic - most models mention moves naturally
  const patterns = [
    /\b([a-h][1-8][a-h][1-8][qrbn]?)\b/g, // e2e4, d2d1=q
    /\b([a-h][1-8])\b/g, // d4, e5
  ];

  for (const pattern of patterns) {
    let match;
    while ((match = pattern.exec(text)) !== null) {
      const move = match[1];
      // Filter for reasonable move patterns
      if (move.length >= 2 && move.length <= 5) {
        moves.add(move);
      }
    }
  }

  return Array.from(moves).slice(0, 3); // Return up to 3 alternatives
}
