/**
 * Types for chess coaching moment detection and explanations
 * Defines interfaces for critical moments and Claude-generated coaching content
 */

/**
 * Reason why a moment is critical
 */
export type MomentReason = 'blunder' | 'brilliant' | 'inaccuracy' | 'key_position' | 'defensive_move';

/**
 * Represents a critical moment in a chess game
 * Detected during position analysis
 */
export interface CriticalMoment {
  /** Index of the move in the game (0-based) */
  readonly moveIndex: number;

  /** Why this moment is critical */
  readonly reason: MomentReason;

  /** Evaluation change in centipawns (negative = worse for player) */
  readonly evaluation: number;

  /** Evaluation before the move */
  readonly previousEvaluation: number;

  /** Confidence score 0-1 (how likely this is a true critical moment) */
  readonly confidence: number;

  /** Best move available at this position */
  readonly bestMove?: string;

  /** The move that was actually played */
  readonly playedMove?: string;
}

/**
 * Coaching explanation for a critical moment
 * Generated by Claude API based on the moment context
 */
export interface CoachingExplanation {
  /** Index of the move being explained */
  readonly moveIndex: number;

  /** Main explanation of the move and position */
  readonly explanation: string;

  /** Alternative moves that could have been played */
  readonly alternatives?: ReadonlyArray<string>;

  /** Follow-up question or advice for the player */
  readonly followUp?: string;

  /** Skill level this explanation was generated for */
  readonly skillLevel?: 'beginner' | 'intermediate' | 'advanced';

  /** Timestamp when explanation was generated */
  readonly generatedAt?: number;
}

/**
 * Configuration for critical moment detection
 * Controls thresholds for identifying different types of moments
 */
export interface CoachingConfig {
  /** Centipawn threshold for blunders (default: 300) */
  readonly blunderThreshold: number;

  /** Centipawn upper threshold for inaccuracies (default: 300) */
  readonly inaccuracyUpperThreshold: number;

  /** Centipawn lower threshold for inaccuracies (default: 50) */
  readonly inaccuracyLowerThreshold: number;

  /** Confidence threshold for including moments (0-1, default: 0.7) */
  readonly confidenceThreshold: number;

  /** Maximum number of moments to detect per game (default: 12) */
  readonly maxMomentsPerGame: number;

  /** Whether to filter duplicate consecutive moments (default: true) */
  readonly filterConsecutiveDuplicates: boolean;

  /** Time limit per position analysis in milliseconds (default: 2000) */
  readonly analysisTimeLimit: number;
}

/**
 * Default configuration for coaching
 */
export const DEFAULT_COACHING_CONFIG: CoachingConfig = {
  blunderThreshold: 300,
  inaccuracyUpperThreshold: 300,
  inaccuracyLowerThreshold: 50,
  confidenceThreshold: 0.7,
  maxMomentsPerGame: 12,
  filterConsecutiveDuplicates: true,
  analysisTimeLimit: 2000,
};

/**
 * Context for generating a coaching explanation
 * Includes position, move, and evaluation information
 */
export interface CoachingContext {
  /** FEN string of the position before the move */
  readonly fen: string;

  /** Move played in algebraic notation (e.g., "e2e4") */
  readonly movePlayed: string;

  /** Best move according to engine (e.g., "e2e4") */
  readonly bestMove: string;

  /** Evaluation before the move (in centipawns) */
  readonly evaluationBefore: number;

  /** Evaluation after the move (in centipawns) */
  readonly evaluationAfter: number;

  /** Principal variation from engine analysis */
  readonly principalVariation?: ReadonlyArray<string>;

  /** Type of moment (blunder, inaccuracy, etc.) */
  readonly momentType: MomentReason;

  /** Move number in the game */
  readonly moveNumber: number;

  /** Game metadata for context */
  readonly gameMetadata?: {
    readonly white?: string;
    readonly black?: string;
    readonly event?: string;
    readonly timeControl?: string;
  };
}
